const NAME_TO_CODE: Record<string, string> = {
  // A
  'afghanistan': 'AF', 'afghan': 'AF',
  'albania': 'AL', 'albanian': 'AL',
  'algeria': 'DZ', 'algerian': 'DZ',
  'angola': 'AO', 'angolan': 'AO',
  'argentina': 'AR', 'argentinian': 'AR', 'argentine': 'AR',
  'armenia': 'AM', 'armenian': 'AM',
  'australia': 'AU', 'australian': 'AU',
  'austria': 'AT', 'austrian': 'AT',
  'azerbaijan': 'AZ', 'azerbaijani': 'AZ',
  // B
  'bahrain': 'BH', 'bahraini': 'BH',
  'bangladesh': 'BD', 'bangladeshi': 'BD',
  'belarus': 'BY', 'belarusian': 'BY',
  'belgium': 'BE', 'belgian': 'BE',
  'belize': 'BZ', 'belizean': 'BZ',
  'benin': 'BJ', 'beninese': 'BJ',
  'bolivia': 'BO', 'bolivian': 'BO',
  'bosnia and herzegovina': 'BA', 'bosnian': 'BA', 'bosnia': 'BA',
  'botswana': 'BW', 'botswanan': 'BW',
  'brazil': 'BR', 'brazilian': 'BR',
  'bulgaria': 'BG', 'bulgarian': 'BG',
  'burkina faso': 'BF', 'burkinabe': 'BF',
  'burundi': 'BI', 'burundian': 'BI',
  // C
  'cambodia': 'KH', 'cambodian': 'KH',
  'cameroon': 'CM', 'cameroonian': 'CM',
  'canada': 'CA', 'canadian': 'CA',
  'cape verde': 'CV', 'cabo verde': 'CV',
  'central african republic': 'CF',
  'chad': 'TD', 'chadian': 'TD',
  'chile': 'CL', 'chilean': 'CL',
  'china': 'CN', 'chinese': 'CN',
  'colombia': 'CO', 'colombian': 'CO',
  'comoros': 'KM', 'comorian': 'KM',
  'congo': 'CG', 'congolese': 'CG',
  'democratic republic of the congo': 'CD', 'dr congo': 'CD', 'drc': 'CD',
  'costa rica': 'CR', 'costa rican': 'CR',
  'croatia': 'HR', 'croatian': 'HR',
  'cuba': 'CU', 'cuban': 'CU',
  'cyprus': 'CY', 'cypriot': 'CY',
  'czech republic': 'CZ', 'czechia': 'CZ', 'czech': 'CZ',
  // D
  'denmark': 'DK', 'danish': 'DK',
  'djibouti': 'DJ', 'djiboutian': 'DJ',
  'dominican republic': 'DO', 'dominican': 'DO',
  // E
  'ecuador': 'EC', 'ecuadorian': 'EC',
  'egypt': 'EG', 'egyptian': 'EG',
  'el salvador': 'SV', 'salvadoran': 'SV',
  'eritrea': 'ER', 'eritrean': 'ER',
  'estonia': 'EE', 'estonian': 'EE',
  'ethiopia': 'ET', 'ethiopian': 'ET',
  // F
  'finland': 'FI', 'finnish': 'FI',
  'france': 'FR', 'french': 'FR',
  // G
  'gabon': 'GA', 'gabonese': 'GA',
  'gambia': 'GM', 'gambian': 'GM',
  'georgia': 'GE', 'georgian': 'GE',
  'germany': 'DE', 'german': 'DE',
  'ghana': 'GH', 'ghanaian': 'GH',
  'greece': 'GR', 'greek': 'GR',
  'guatemala': 'GT', 'guatemalan': 'GT',
  'guinea': 'GN', 'guinean': 'GN',
  'guinea-bissau': 'GW',
  'equatorial guinea': 'GQ',
  // H
  'haiti': 'HT', 'haitian': 'HT',
  'honduras': 'HN', 'honduran': 'HN',
  'hungary': 'HU', 'hungarian': 'HU',
  // I
  'india': 'IN', 'indian': 'IN',
  'indonesia': 'ID', 'indonesian': 'ID',
  'iran': 'IR', 'iranian': 'IR',
  'iraq': 'IQ', 'iraqi': 'IQ',
  'ireland': 'IE', 'irish': 'IE',
  'israel': 'IL', 'israeli': 'IL',
  'italy': 'IT', 'italian': 'IT',
  'ivory coast': 'CI', "cote d'ivoire": 'CI', 'ivorian': 'CI',
  // J
  'jamaica': 'JM', 'jamaican': 'JM',
  'japan': 'JP', 'japanese': 'JP',
  'jordan': 'JO', 'jordanian': 'JO',
  // K
  'kazakhstan': 'KZ', 'kazakhstani': 'KZ',
  'kenya': 'KE', 'kenyan': 'KE',
  'kuwait': 'KW', 'kuwaiti': 'KW',
  // L
  'laos': 'LA', 'laotian': 'LA',
  'latvia': 'LV', 'latvian': 'LV',
  'lebanon': 'LB', 'lebanese': 'LB',
  'lesotho': 'LS', 'mosotho': 'LS',
  'liberia': 'LR', 'liberian': 'LR',
  'libya': 'LY', 'libyan': 'LY',
  'lithuania': 'LT', 'lithuanian': 'LT',
  // M
  'madagascar': 'MG', 'malagasy': 'MG',
  'malawi': 'MW', 'malawian': 'MW',
  'malaysia': 'MY', 'malaysian': 'MY',
  'mali': 'ML', 'malian': 'ML',
  'mauritania': 'MR', 'mauritanian': 'MR',
  'mauritius': 'MU', 'mauritian': 'MU',
  'mexico': 'MX', 'mexican': 'MX',
  'moldova': 'MD', 'moldovan': 'MD',
  'mongolia': 'MN', 'mongolian': 'MN',
  'morocco': 'MA', 'moroccan': 'MA',
  'mozambique': 'MZ', 'mozambican': 'MZ',
  'myanmar': 'MM', 'burmese': 'MM', 'burma': 'MM',
  // N
  'namibia': 'NA', 'namibian': 'NA',
  'nepal': 'NP', 'nepali': 'NP',
  'netherlands': 'NL', 'dutch': 'NL',
  'new zealand': 'NZ',
  'nicaragua': 'NI', 'nicaraguan': 'NI',
  'niger': 'NE', 'nigerien': 'NE',
  'nigeria': 'NG', 'nigerian': 'NG',
  'north korea': 'KP', 'north korean': 'KP',
  'norway': 'NO', 'norwegian': 'NO',
  // O
  'oman': 'OM', 'omani': 'OM',
  // P
  'pakistan': 'PK', 'pakistani': 'PK',
  'palestine': 'PS', 'palestinian': 'PS',
  'panama': 'PA', 'panamanian': 'PA',
  'paraguay': 'PY', 'paraguayan': 'PY',
  'peru': 'PE', 'peruvian': 'PE',
  'philippines': 'PH', 'filipino': 'PH', 'philippine': 'PH',
  'poland': 'PL', 'polish': 'PL',
  'portugal': 'PT', 'portuguese': 'PT',
  // Q
  'qatar': 'QA', 'qatari': 'QA',
  // R
  'romania': 'RO', 'romanian': 'RO',
  'russia': 'RU', 'russian': 'RU',
  'rwanda': 'RW', 'rwandan': 'RW',
  // S
  'saudi arabia': 'SA', 'saudi': 'SA',
  'senegal': 'SN', 'senegalese': 'SN',
  'serbia': 'RS', 'serbian': 'RS',
  'sierra leone': 'SL', 'sierra leonean': 'SL',
  'singapore': 'SG', 'singaporean': 'SG',
  'somalia': 'SO', 'somali': 'SO',
  'south africa': 'ZA', 'south african': 'ZA',
  'south korea': 'KR', 'south korean': 'KR', 'korean': 'KR',
  'south sudan': 'SS', 'south sudanese': 'SS',
  'spain': 'ES', 'spanish': 'ES',
  'sri lanka': 'LK', 'sri lankan': 'LK',
  'sudan': 'SD', 'sudanese': 'SD',
  'swaziland': 'SZ', 'eswatini': 'SZ',
  'sweden': 'SE', 'swedish': 'SE',
  'switzerland': 'CH', 'swiss': 'CH',
  'syria': 'SY', 'syrian': 'SY',
  // T
  'taiwan': 'TW', 'taiwanese': 'TW',
  'tajikistan': 'TJ', 'tajik': 'TJ',
  'tanzania': 'TZ', 'tanzanian': 'TZ',
  'thailand': 'TH', 'thai': 'TH',
  'togo': 'TG', 'togolese': 'TG',
  'tunisia': 'TN', 'tunisian': 'TN',
  'turkey': 'TR', 'turkish': 'TR',
  'turkmenistan': 'TM', 'turkmen': 'TM',
  // U
  'uganda': 'UG', 'ugandan': 'UG',
  'ukraine': 'UA', 'ukrainian': 'UA',
  'united arab emirates': 'AE', 'uae': 'AE', 'emirati': 'AE',
  'united kingdom': 'GB', 'uk': 'GB', 'british': 'GB', 'great britain': 'GB', 'england': 'GB',
  'united states': 'US', 'usa': 'US', 'american': 'US',
  'uruguay': 'UY', 'uruguayan': 'UY',
  'uzbekistan': 'UZ', 'uzbek': 'UZ',
  // V
  'venezuela': 'VE', 'venezuelan': 'VE',
  'vietnam': 'VN', 'vietnamese': 'VN',
  // Y
  'yemen': 'YE', 'yemeni': 'YE',
  // Z
  'zambia': 'ZM', 'zambian': 'ZM',
  'zimbabwe': 'ZW', 'zimbabwean': 'ZW',
};

const CODE_TO_NAME: Record<string, string> = {
  'AF': 'Afghanistan', 'AL': 'Albania', 'DZ': 'Algeria', 'AO': 'Angola',
  'AR': 'Argentina', 'AM': 'Armenia', 'AU': 'Australia', 'AT': 'Austria',
  'AZ': 'Azerbaijan', 'BH': 'Bahrain', 'BD': 'Bangladesh', 'BY': 'Belarus',
  'BE': 'Belgium', 'BZ': 'Belize', 'BJ': 'Benin', 'BO': 'Bolivia',
  'BA': 'Bosnia and Herzegovina', 'BW': 'Botswana', 'BR': 'Brazil',
  'BG': 'Bulgaria', 'BF': 'Burkina Faso', 'BI': 'Burundi', 'KH': 'Cambodia',
  'CM': 'Cameroon', 'CA': 'Canada', 'CV': 'Cape Verde', 'CF': 'Central African Republic',
  'TD': 'Chad', 'CL': 'Chile', 'CN': 'China', 'CO': 'Colombia',
  'KM': 'Comoros', 'CG': 'Congo', 'CD': 'Democratic Republic of the Congo',
  'CR': 'Costa Rica', 'HR': 'Croatia', 'CU': 'Cuba', 'CY': 'Cyprus',
  'CZ': 'Czech Republic', 'DK': 'Denmark', 'DJ': 'Djibouti',
  'DO': 'Dominican Republic', 'EC': 'Ecuador', 'EG': 'Egypt',
  'SV': 'El Salvador', 'GQ': 'Equatorial Guinea', 'ER': 'Eritrea',
  'EE': 'Estonia', 'ET': 'Ethiopia', 'FI': 'Finland', 'FR': 'France',
  'GA': 'Gabon', 'GM': 'Gambia', 'GE': 'Georgia', 'DE': 'Germany',
  'GH': 'Ghana', 'GR': 'Greece', 'GT': 'Guatemala', 'GN': 'Guinea',
  'GW': 'Guinea-Bissau', 'HT': 'Haiti', 'HN': 'Honduras', 'HU': 'Hungary',
  'IN': 'India', 'ID': 'Indonesia', 'IR': 'Iran', 'IQ': 'Iraq',
  'IE': 'Ireland', 'IL': 'Israel', 'IT': 'Italy', 'CI': 'Ivory Coast',
  'JM': 'Jamaica', 'JP': 'Japan', 'JO': 'Jordan', 'KZ': 'Kazakhstan',
  'KE': 'Kenya', 'KW': 'Kuwait', 'LA': 'Laos', 'LV': 'Latvia',
  'LB': 'Lebanon', 'LS': 'Lesotho', 'LR': 'Liberia', 'LY': 'Libya',
  'LT': 'Lithuania', 'MG': 'Madagascar', 'MW': 'Malawi', 'MY': 'Malaysia',
  'ML': 'Mali', 'MR': 'Mauritania', 'MU': 'Mauritius', 'MX': 'Mexico',
  'MD': 'Moldova', 'MN': 'Mongolia', 'MA': 'Morocco', 'MZ': 'Mozambique',
  'MM': 'Myanmar', 'NA': 'Namibia', 'NP': 'Nepal', 'NL': 'Netherlands',
  'NZ': 'New Zealand', 'NI': 'Nicaragua', 'NE': 'Niger', 'NG': 'Nigeria',
  'KP': 'North Korea', 'NO': 'Norway', 'OM': 'Oman', 'PK': 'Pakistan',
  'PS': 'Palestine', 'PA': 'Panama', 'PY': 'Paraguay', 'PE': 'Peru',
  'PH': 'Philippines', 'PL': 'Poland', 'PT': 'Portugal', 'QA': 'Qatar',
  'RO': 'Romania', 'RU': 'Russia', 'RW': 'Rwanda', 'SA': 'Saudi Arabia',
  'SN': 'Senegal', 'RS': 'Serbia', 'SL': 'Sierra Leone', 'SG': 'Singapore',
  'SO': 'Somalia', 'ZA': 'South Africa', 'KR': 'South Korea', 'SS': 'South Sudan',
  'ES': 'Spain', 'LK': 'Sri Lanka', 'SD': 'Sudan', 'SZ': 'Eswatini',
  'SE': 'Sweden', 'CH': 'Switzerland', 'SY': 'Syria', 'TW': 'Taiwan',
  'TJ': 'Tajikistan', 'TZ': 'Tanzania', 'TH': 'Thailand', 'TG': 'Togo',
  'TN': 'Tunisia', 'TR': 'Turkey', 'TM': 'Turkmenistan', 'UG': 'Uganda',
  'UA': 'Ukraine', 'AE': 'United Arab Emirates', 'GB': 'United Kingdom',
  'US': 'United States', 'UY': 'Uruguay', 'UZ': 'Uzbekistan',
  'VE': 'Venezuela', 'VN': 'Vietnam', 'YE': 'Yemen', 'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
};

const SORTED_NAMES = Object.keys(NAME_TO_CODE).sort((a, b) => b.length - a.length);

export function getCountryName(code: string): string {
  return CODE_TO_NAME[code.toUpperCase()] || code;
}

export function findCountryInText(text: string): string | null {
  const lower = text.toLowerCase();
  for (const name of SORTED_NAMES) {
    const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    if (new RegExp(`(?:^|[^a-z])${escaped}(?:[^a-z]|$)`).test(lower)) {
      return NAME_TO_CODE[name];
    }
  }
  return null;
}
